version: "3.6"

services:
    app:
        build:
            context: .
        volumes:
            - static_data:/vol/static
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - STATIC_ROOT=${STATIC_ROOT}
    proxy:
        build:
            context: ./nginx
        volumes:
            - static_data:/vol/static
        ports:
            - "80:8080"
            - "443:8443"
        depends_on:
            - app

volumes:
    static_data:
