# Generated by Django 3.1.2 on 2020-10-26 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_tag_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='moderators',
            field=models.ManyToManyField(related_name='user_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(related_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
