# Generated by Django 3.1.2 on 2020-10-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20201026_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='moderators',
        ),
    ]
