# Generated by Django 3.1.2 on 2020-10-28 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0004_remove_tag_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='moderators',
            field=models.ManyToManyField(related_name='user_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
